name = "Vidda"
description = "A simple application that uses pandas and folium to draw heatmaps on a map."
packages = ["folium", "pandas", "numpy", "pillow","pyodide-http", "requests", "asyncio", "trimesh"]
